### ISSUE TITLE
JDump not working - Component Not Found Error

### ISSUE THREAD

**Issue by spurgeonbj** [schnuti/files#1]
Dear Ove,

Greetings of the season!!

While trying to run dumpVar() or access the J!dump component from the admin menu, it says component not found. Aparently, the zip file doesnt contain the component stuff... Can you please help...

**Comment by schnuti** [comment]
Hi @spurgeonbj,
for what Joomla version did you install it? Didn't you see some error messages? This JDump version do not work with the latest Joomla 4.0 alphas or beta versions. I did not yet upload the version I use (now in J-beta-1 ). As Joomla now is in the beta-phase nothing unexpected should happen in the basic code classes.
If you want to use it, I'll make a new package, a quick installation test and upload it here over the weekend. --- I use it all the time to trace my own bugs ;)

**Comment by schnuti** [comment]
@spurgeonbj 
I uploaded new packaged files tested with Joomla 4.0 beta 1 - XAMPP on Windows.
Install as normal. Do not forget to activate the plugin. You can do that in the component view!

**Comment by spurgeonbj** [comment]
Dear Ove, Thanks a ton for your kind and quick followup. I was trying with latest joomla stable 3.9.14 on lamp stack. The error was 'Error 404 - Component not found';

Doesnt work, yet for me. Same error...

Thanks once again!!

**Comment by schnuti** [comment]
This version of JDump is for Joomla 4 only! It's a fork from the old original modified to work with J 4.
For Joomla 3.x I suppose the old version still works. 
On GitHub: https://github.com/mathiasverraes/jdump
This version could eventually work with J 3.10. If that version gets compatible with J 4.0. (Namespacing and more)

**Comment by spurgeonbj** [comment]
Thanks a ton for your kind and lightning response! 

So this is not compatible with Joomla 3.9.x .

**Comment by schnuti** [comment]
Funny that it installs on Joomla 3.x. It shouldn't. I've set the min version to 3.10 in the xml-package file. Hmmm?
I made a quick test on a J3 instance and got the same as you. It installs but can of course not be started as files needed are not present in a J4 version.

Be sure to UNINSTALL this version before you install a J3 version or it could all be messed up! It did uninstall correct in my test.

You should have read the README on the page with the zip-file ;)

You are welcome back the day you start coding for J4!

**Comment by spurgeonbj** [comment]
Dear Ove,

Greetings!!

Yes! Guess because the current joomla version is 3.14? which is greater
than 3.10...

Yeah, I uninstalled it and there was a bug in uninstall script i guess, so
deleted the plugin entry from extensions table and then installed what you
suggested.

That also didnt install with the ready made package available on the git
page, so had to build with composer / phing and install it. Now it works.

Thanks a ton!! Looking forward to J4 development with your Jdump!!!

**Comment by schnuti** [comment]
You learn every day. I found that Joomla doesn't have any version checks built in. It was discussed a lot at the start of J3 but obviously nothing was implemented. Maybe I should write an installation script only to check if J4 is running? I'll do it, if I have to update something else. Latest J3 is minor version 9 patch 14.

I could have warned you. As I remember, the old JDump zip file is not a package. You have to unzip it and install component and plugin separately. i.e. composer/phing not needed.

**Comment by spurgeonbj** [comment]
So kind of you to follow up on this and share the info, dear Ove!! God
bless you!!

Thanks for correcting me on Joomla version.

And for tips on installing jdump!!

**Comment by fontanil** [comment]
Hi,
I have that error on a 4beta1dev (404 View not found...) (PHP 7.4)
This morning I tried on another test site (last nighty build, PHP 7.4) on a other server/host. No problem to install, plugin activated, in first position, menu link for frontend: when i click the administrator menu link, the site opens the main administrator page. Absolutly no error, though the error reporting is set to "development" and debug system to "Yes".
Thanks for your work!

PS: on a very new test site on a third host server and PHP 7.3.13 (only J! 4beta1dev nighty build from today 24 feb. and J!dump) I have the same error 404.

**Comment by schnuti** [comment]
Do you have any idea why there are problems? Did you try to install another extension/utility from a downloaded zip/package? Sorry, I have no clue.

**Comment by fontanil** [comment]
I'm using Akeeba backup, JCE, LazyDbBackup without error.
For the moment, I don't understand why I have a 404 error on two tests sites and no error (perhaps a server configuration?) on the third (3 different remote servers).

**Comment by schnuti** [comment]
Do you install those extensions from a zip or from the web?

**Comment by fontanil** [comment]
Always from a zip

In the logs: "[24/Feb/2020:11:29:12 +0100] "GET /administrator/index.php?option=com_jdump HTTP/1.0" 303" with no error and opening of the main administrator page

**Comment by schnuti** [comment]
So we still don't have a clue! Please let me know if "a lightning strikes you" ;)

**Comment by schnuti** [comment]
Are those extensions "real" J 4 versions? i.e. namespaced  and more? But this should not really touch the installation process.

**Comment by fontanil** [comment]
They are Joomla! 3 extensions made compatible with Joomla! 4
I have no problem with installation of J!dump, only errors 404 or 303 when trying to open the J!dump component page.

**Comment by schnuti** [comment]
@spurgeonbj 
Sorry for hijacking this thread. But it may be interesting for you to.
I did not recognize the change of issue,
